services:
  loki:
    container_name: loki
    image: grafana/loki:2.9.2
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observable-universe
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '7777:3000'
    volumes:
      - ./grafana-ds.yaml:/etc/grafana/provisioning/datasources/grafana-ds.yaml
    networks:
      - observable-universe
  tempo:
    container_name: tempo
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - ":3200:3200"   # tempo
      - "14317:4317"  # otlp grpc
      - "14318:4318"  # otlp http
    networks:
      - observable-universe
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    depends_on:
      - loki
      - grafana
      - tempo
    networks:
      - observable-universe


networks:
  observable-universe:


