services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    networks:
      - observable-universe
  loki:
    container_name: loki
    image: grafana/loki:2.9.2
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observable-universe
#  promtail:
#    image: grafana/promtail:2.9.2
#    volumes:
#      - ./promtail-config.yml:/etc/promtail/config.yml
#    command: -config.file=/etc/promtail/config.yml
#    networks:
#      - observable-universe

networks:
  observable-universe:


