# Configuration file version
apiVersion: 1

datasources:
  - name: loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    orgId: 1
    basicAuth: false
    isDefault: false
    version: 1
    editable: false

  - name: tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    orgId: 1
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-4h'
        spanEndTimeShift: '+4h'
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{exporter="OTLP"} |= "$${__span.traceId}" |= "$${__span.spanId}"'
