receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: detailed
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
#  otlp:
#    endpoint: localhost:4317

service:
  pipelines:
#    traces:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [otlp]
#    metrics:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [loki]
