receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: detailed
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  otlp/tempo:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true
#  otlp:
#    endpoint: tempo:14317
#    tls:
#      insecure: true
#  otlp:
#    endpoint: localhost:4317

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo]
#    metrics:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [loki]
