server:
  http_listen_port: 9080
  grpc_listen_port: 9095

positions:
  filename: ./positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels: # The path to load logs from. Can use glob patterns (e.g., /var/log/*.log).
          job: varlogs # log tag
          __path__: /var/log/*log